create table Class12B
(RedgNo char(10),
Name varchar(20),
Tmarks int(3),
City varchar(20));
insert into Class12B values('Y03130', 'K. Narayanan', 458, 'Chennai');
insert into Class12B values('Y02112', 'M. Padmanavan', 432, 'Bengaluru');
insert into Class12B values('Y01111', 'N. Maria', 454, 'Kochi');
insert into Class12B values('Y01140', 'Piush Cocher', 464, 'Ludhiana');
insert into Class12B values('Y02150', 'N. N. Rao', 487, 'New Delhi');
insert into Class12B values('Y00117', 'Kavita Krishnamurty', 436, 'Bengaluru');

