create table Class12A
(RedgNo char(10),
Name varchar(20),
Tmarks int(3),
City varchar(20));
insert into Class12A values('Y01100', 'Amit Kumar', 450, 'New Delhi');
insert into Class12A values('Y00102', 'Aasha Goel', 426, 'Lucknow');
insert into Class12A values('Y00117', 'Kavita Krishnamurty', 436, 'Bengaluru');
insert into Class12A values('Y02110', 'Riya Mary', 446, 'Chennai');
insert into Class12A values('Y01140', 'Piush Cocher', 464, 'Ludhiana');
insert into Class12A values('Y02107', 'Om Berma', 476, 'New Delhi');
