                if (To=="Dubai Healthcare City"):
                     message3= ["The feeder buses available are:","22-Healthcare city-Al Nahda 1"",""42-GHUBAIBA BUS STATION :Al Ghubaiba 1"",""C7-HOR AL ANZ BUS STATION-HEALTHCARE CITY"]
                if (To=="]Rashidiya "]):
                     message3= ["The feeder buses available are:","F1- Ras Al Khor","F2-Mirdif West","F5-Al Mizhar","F10-Al Warqa","365-International City"]
                if(To=="Emirates"):
                     message3= ["The feeder buses available are:","F8-Al Nahda 2-Mamzar ,Century Mall"]
                if(To=="Airport Terminal-3"):
                     message3= ["The feeder buses available are:","C1-Satwa Bus Station","88-Nakheel MS"]
                if(To=="Airport Terminal-1"):
                     message3= ["The feeder buses available are:","C1-Satwa Bus Station","4-Gold Souq Bus Station-Rashidiya MS","11A-Gold souq Bus Station-Al Awir Terminus","32C-Al Qusais-1 Bus Station-Satwa Bus Station","33-Ghubaiba Bus Station-Al Qusais-1 Bus Station","42-Ghubaiba Bus Station-Airport Airport Terminal-1","48-Mamzar","Century Mall-Rashidiya  MS","64A-Glod Souk Bus Station-Ras Al Khor","88-Airport Airport Terminal-3-Nakheel MS"]
                if(To=="GGICO"):
                     message3= ["The feeder buses available are:","42-Ghubaiba Bus Station-airport Airport Terminal-1"]
                if(To=="Deira City Centre"):
                     message3= ["The feeder buses available are:","C10-Hamriya Port- Jumeirah Beach Park","C14-Mamzar","Century Mall-Safa Terminus","C15-Hamriya Port-Al Wasl Park Terminus","C19-Ghubaiba Bus Station-Al Qusais-1 Industrial Area","X28-Lulu Village-Nakheel MS","22-Health Care City-Al Nahda 1 ","27-Gold Souq Bus Station-Dubai Mall","33-Ghubaiba Bus Station-Al Qusais-1 Bus Station","53-Ghubaiba Bus Station-International City","88-Airport Airport Terminal-3-Nakhell MS"]
                if(To=="Al Rigga"):
                     message3= ["The feeder buses available are:","C9-Satwa Bus Station-Hor Al Anz East"]
                if(To=="Union Square"):
                     message3= ["The feeder buses available are:","C1-Airport Airport Terminal-3-Satwa Bus Station","C2-Zabeel Park-Airport Terminal 2","C4-Gold Souq Bus Station-Jadaf","C5-Gold Souq bus Station-Ghubaiab Bus Satation","C7-Hor Al Anz Bus Station-Healthcare City","C9-Satwa Bus Station-Hor Al Anz East ","C28-Gold Souq Bus Station-Mamzar Beach Park","C55-Gold Souq Bus Station-Ghubaiba Bus Station","E303-Union Square Square MS-Sharjah","E700-Fujairah-Union Square Square MS","E400-Union Square Square MS-Ajman","X94-Gold Souq Bus Station-Dubai Investment Park","4-Gold Souq Bus Station-Rashidiya  MS","11A-Gold Souq Bus Station-Al Awir Terminus","27-Gold Souq Bus Station-Dubai Mall","64A-Gold Souq Bus Station-Ras Al Khor"]
                if(To=="Burjuman"):
                     message3= "The feeder buses available are:","C2-Zabeel Park-Airport Terminal 2","C3-Hor Al Anz Bus Station-Karama Bus Station","C5-Gold Souq Bus Station-Ghubaiba Bus Station","C10-Hamriya Port-Jumeirah Beach Park","C18-Shaikh Rashid Colony","AlQusais-Lamcy Plaza    ","C19-Ghubaiba Bus Station-Al Qusais-1 Industrial Area","C55-Gold Souq Bus Station-Ghubaiba Bus Station","X23-Gold Souq Bus Station–International City","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4","33-Ghubaiba Bus Station–Al Qusais-1 Bus Station","42-Ghubaiba Bus Station–Airport Airport Terminal-1","44-Ghubaiba Bus Station–Dubai Festival City","61-Ghubaiba Bus Station–Ras Al Khor","61D-Ghubaiba Bus Station–Nad Al Sheba Clinic ","66-Ghubaiba Bus Station–Faqa Terminus","67-Ghubaiba Bus Station–Endurance City Terminus","91-Ghubaiba Bus Station–Jebel Ali Bus Station"]
                if(To=="Al Karama"):
                     message3= ["The feeder buses available are:","C2-Airport Terminal 2–Zabeel Park","C10-Hamriya Port–Jumeirah Beach Park","C15 Hamriya Port–Al Wasl Park","C26-Al Wasl Park–Al Qusais-1 Industrial Area","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4","61-Ghubaiba Bus Station–Ras Al Khor Industrial Area","88-Airport Airport Terminal-3–Nakheel MS"]
                if(To=="Al Jafiliya"):
                     message3= ["The feeder buses available are:","C2-Zabeel Park–Airport Terminal 2","C15-Hamriya Port–Al Wasl Park Terminus","C26-Al Wasl Park Terminus–Al Qusais-1 Industrial Area","X10-Gold Souq Bus Station–Al Quoz Bus Station","X28-Lulu Village–Nakheel MS","X92-Ghubaiba Bus Station–Dubai Investment Park","10-Gold Souq Bus Station–Al Quoz Bus Station ","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4","27-Gold Souq Bus Station-Dubai Mall","61-Ghubaiba Bus Station–Ras Al Khor Ind. Area","88-Airport Airport Terminal-3–Nakheel MS"]
                if(To=="Dubai World Trade Centre "):
                     message3= ["The feeder buses available are:","F11-Financial Centre MS–Satwa","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4","98E-Satwa Bus Station–Al Quoz Ind. Area 3"]
                if(To=="Emirates Towers"):
                     message3= ["The feeder buses available are:","F11 Financial Centre MS – Satwa","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4","27-Gold Souq Bus Station–Dubai Mall","98E-Satwa Bus Station–Al Quoz Ind. Area 3"]
                if(To=="Dubai International Financial Centre "):
                     message3= ["The feeder buses available are:","F11-Financial Centre MS–Satwa"] 
                if(To=="Burj Khalifa / Dubai Mall"):
                     message3= ["The feeder buses available are:","F13-Burj Khalifa/Dubai Mall MS–Dubai Mall","F16-Burj Khalifa/Dubai Mall MS–Jumeirah 2"]
                if(To=="Business Bay"):
                     message3= ["The feeder buses available are:","F16 Dubai Mall – Jumeirah 2","F20 Business Bay MS – Al Safa 1","7-Ghubaiba Bus Station–Iranian Clinic Al Quoz"]
                if(To=="Noor Islamic Bank"):
                     message3= ["The feeder buses available are:","F15-Noor Islamic Bank MS–Al Quoz Ind. Area 2 ","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4"]
                if(To=="First Gulf Bank"):
                     message3= ["The feeder buses available are:","F25-First Gulf Bank MS land side–Al Quoz 3 & 4","12-Ghubaiba Bus Station–Al Quoz Bus Station"]
                if(To=="Mall of the Emirates"):
                     message3= ["The feeder buses available are:","F30-Mall of the Emirates MS–Arabian Ranches","F33-Mall of the Emirates MS–Al Barsha 3","93-Ghubaiba Bus Station–The Greens"]
                if(To=="Dubai Internet City"):
                     message3= ["The feeder buses available are:","F31-The Meadows–Dubai Internet City MS","88-Airport Airport Terminal-3–Nakheel MS","X28-Lulu Village–Nakheel MS"] 
                if(To=="Nakheel"):
                     message3= ["The feeder buses avaliable are:","X28-Lulu Village-Nakheel MS","88-Airport Airport Terminal-3–Nakheel MS"]
                if(To=="Dubai Marina"):
                     message3= ["The feeder buses avaliable are:","F37-Marina MS–Dubai Marina"]
                if(To=="Jumeirah Lake Towers"):
                     message3= ["The feeder buses available are:","F37-Marina MS–Jumeirah Lakes Tower MS–Dubai Marina"]
                if(To=="Ibn Battuta"):
                     message3= ["The feeder buses avaliable are:","E101-Abu Dhabi–Ibn Batutta","F43-Ibn Battuta MS–Discovery Gardens","F44-Ibn Battuta MS–The Gardens","F46-Ibn Battuta MS–IMP Zone","F48-Ibn Battuta MS–Dubai Investment Park","F53-Ibn Battuta MS–Dubai Industrial City","8-Ibn Battuta MS–Gold Souk Bus Station"]
                if(To=="Jebel Ali"):
                     message3= ["The feeder buses avaliable are:","F54-Jafza South–Jebel Ali MS","99-New East Camp–Marine Control Towers"]
                if(To=="Jebel Ali Industrial"):
                     message3= ["The feeder buses avaliable are:","F54-Jafza South–Jebel Ali MS","99-New East Camp–Marine Control Towers"]
                    

                    
                if(To=="Etisalat"):
                     message3= ["The feeder buses avaliable are:","31-Gold Souq Bus Station–Oud Al Mateena"]
                if(To=="Al Qusais-1"):
                     message3= ["The feeder buses avaliable are:","13 Gold Souq Bus Station – Al Qusais-1 Bus Station","31-Gold Souq Bus Station–Oud Al Mateena","64-Gold Souq Bus Station–Ras Al Khor"]
                if(To=="Airport Free Zone"):
                     message3= ["The feeder buses avaliable are:","13-Gold Souq Bus Station–Al Qusais-1 Bus Station","17-Al Sabkha Bus Station–Al Qusais-1 Bus Station ","31-Gold Souq Bus Station–Oud Al Mateena","64-Gold Souq Bus Station–Ras Al Khor","C18-Shaikh Rashid Colony"," Al Qusais-1–Lamcy Plaza ","C19-Ghubaiba Bus Station–Al Qusais-1 Industrial Area","x28-Lulu Village–Nakheel MS"]
                if(To=="Al Nahda"):
                     message3= ["The feeder buses avaliable are:","13 Gold Souq Bus Station–Al Qusais-1 Bus Station","13A Gold Souq Bus Station–Al Qusais-1 Bus Station","17 Al Sabkha Bus Station–Al Qusais-1 Bus Station","22 Healthcare City–Al Nahda 1","31 Gold Souq Bus Station–Oud Al Mateena","64 Gold Souq Bus Station–Ras Al Khor","C18 Shaikh Rashid Colony"," Al Qusais-1–Lamcy Plaza","C19 Ghubaiba Bus Station–Al Qusais-1 Industrial Area","X28 Lulu Village–Nakheel MS"]
                if(To=="Rashid Stadium"):
                     message3= ["The feeder buses available are:","13-Gold Souq Bus Station–Al Qusais-1 Bus Station","13A Gold Souq Bus Station–Al Qusais-1 Bus Station","17 Al Sabkha Bus Station–Al Qusais-1 Bus Station","22 Healthcare City–Al Nahda 1","64 Gold Souq Bus Station–Ras Al Khor","C18 Shaikh Rashid Colony"," Al Qusais-1–Lamcy Plaza","C19 Ghubaiba Bus Station–Al Qusais-1 Industrial Area","X28 Lulu Village–Nakheel MS"]
                if(To=="Al Qiyadah"):
                     message3= ["The feeder buses available are:","C9-Al Satwa Bus Station–Hor Al Anz East"]
                if(To=="Abu Hail"):
                     message3= ["The feeder buses available are:","13 Gold Souq Bus Station–Al Qusais-1 Bus Station","13A Gold Souq Bus Station–Al Qusais-1 Bus Station","48 Mamzar"," Century Mall–Al Rashidiya  MS","C2 Zabeel Park–Airport Terminal 2","C3 Hor Al Anz Bus Station–Karama Bus Station","C7 Hor Al Anz Bus Station–Healthcare City","C9 Satwa Bus Station–Hor Al Anz East","C19 Ghubaiba Bus Station–Al Qusais-1 Industrial Area","X28 Lulu Village–Nakheel MS"]
                if(To=="Abu Bakr Seddiq"):
                     message3= ["The feeder buses available are:","13 Gold Souq Bus Station–Al Qusais-1 Bus Station","13A Gold Souq Bus Station–Al Qusais-1 Bus Station","48 Mamzar"," Century Mall–Al Rashidiya  MS","C2 Zabeel Park–Airport Terminal 2","C19 Ghubaiba Bus Station–Al Qusais-1 Industrial Area","x28 Lulu Village–Nakheel MS"] 
                if(To=="Salahuddin"):
                     message3= ["The feeder buses available are:","10-Gold Souq Bus Station–Al Quoz Bus Station","13-Gold Souq Bus Station–Al Qusais-1 Bus Station","13A-Gold Souq Bus Station–Al Qusais-1 Bus Station","C2-Zabeel Park–Airport Terminal 2","C28-Gold Souq Bus Station–Mamzar Beach Park"]
                
                if(To=="Baniyas Square"):
                     message3= ["The feeder buses available are:","17-Al Sabkha Bus Station–Al Qusais-1 Bus Station","64A-Gold Souq Bus Station–Ras Al Khor"]
                if(To=="]Palm Deira"]):
                     message3= ["The feeder buses available are:","8-Gold Souq Bus Station–Al Mina Al Siyahi","C1-Airport Airport Terminal-3–Satwa Bus Station","C2-Zabeel Park–Airport Terminal 2","C3-Hor Al Anz Bus Station-Karama Bus Station","C7-Hor Al Anz Bus Station–Healthcare City","C9-Satwa Bus Station–Hor Al Anz East","C18-Shaikh Rashid Colony"," Al Qusais-1–Lamcy Plaza","C55-Gold Souq Bus Station–Ghubaiba Bus Station","X10-Gold Souq Bus Station–Al Qouz Bus Station","X13-LuLu Village–Al Satwa Bus Station","X23-Gold Souq Bus Station–International City"]
                if(To=="Al Ras"):
                     message3= ["The feeder buses available are:","27-Gold Souq Bus Station–Dubai Mall","53-Ghubaiba Bus Station–International City","C2-Zabeel Park–Airport Terminal 2","C4-Gold Souq Bus Station–Jadaf","C7-Hor Al Anz Bus Station–Healthcare City","C9-Satwa Bus Station–Hor Al Anz East","C28-Gold Souq Bus Station–Mamzar Beach Park","C55-Gold Souq Bus Station–Ghubaiba Bus Station"]
                if(To=="Al Ghubaiba"):
                     message3= ["The feeder buses available are:","8-Gold Souq Bus Station–Al Mina Al Siyahi","C5-Gold Souq Bus Station–Ghubaiba Bus Station","C7-Hor Al Anz Bus Station–Healthcare City","C9-Satwa Bus Station–Hor Al Anz East","X13-LuLu Village–Al Satwa Bus Station"]    
                if(To=="Al Fahidi"):
                     message3= ["The feeder buses available are:","21-Ghubaiba Bus Station–Al Quoz Ind. Area 4","33-Ghubaiba Bus Station–Qusais Bus Station","42-Ghubaiba Bus Station–Airport Airport Terminal-1 ","44-Ghubaiba Bus Station–Dubai Festival City","61-Ghubaiba Bus Station–Ras Al Khor","61D-Ghubaiba Bus Station-Nad Al Sheba Clinic","66-Ghubaiba Bus Station–Faqa Terminus","67-Ghubaiba Bus Station–Endurance City Terminus","91-Ghubaiba Bus Station–Jebel Ali Bus Station","C1-Airport Airport Terminal-3–Satwa Bus Station","C2-Zabeel Park–Airport Terminal 2","C3-Hor Al Anz Bus Station–Karama Bus Station","C5-Gold Souq Bus Station–Ghubaiba Bus Station","C7-Hor Al Anz Bus Station–Healthcare City","C18-Shaikh Rashid Colony,Al Qusais-1–Lamcy Plaza","C19-Ghubaiba Bus Station-Al Qusais-1 Industrial Area","C55-Gold Souq Bus Station-Ghubaiba Bus Station","X23-Gold Souq Bus Station–International City"]
                if(To=="Oud Metha"):
                     message3= ["The feeder buses available are:","22-Healthcare City – Al Nahda 1","42-Ghubaiba Bus Station-Airport Airport Terminal-1","44-Ghubaiba Bus Station-Dubai Festival City","61D-Ghubaiba Bus Station-Nad Al Sheba Clinic","66-Ghubaiba Bus Station-Faqa Terminus","67-Ghubaiba Bus Station-Endurance City Terminus","C4-Gold Souq Bus Station-Jadaf","C7-Hor Al Anz Bus Station-Healthcare City","C18-Shaikh Rashid Colony"," Al Qusais-1-Lamcy Plaza","X23-Gold Souq Bus Station–International City"]
