if(To=="etisalat"):
    print "31-Gold Souq Bus Station–Oud Al Mateena"
if(To=="al qusais"):
    print "13 Gold Souq Bus Station – Al Qusais Bus Station"
    print "31-Gold Souq Bus Station–Oud Al Mateena"
    print "64-Gold Souq Bus Station–Ras Al Khor"
if(To=="dubai airport freezone"):
    print "13-Gold Souq Bus Station–Al Qusais Bus Station"
    print "17-Al Sabkha Bus Station–Al Qusais Bus Station" 
    print "31-Gold Souq Bus Station–Oud Al Mateena"
    print "64-Gold Souq Bus Station–Ras Al Khor"
    print "C18-Shaikh Rashid Colony, Al Qusais–Lamcy Plaza" 
    print "C19-Ghubaiba Bus Station–Al Qusais Industrial Area"
    print "x28-Lulu Village–Nakheel MS"
if(To=="al nahda"):
    print "13 Gold Souq Bus Station–Al Qusais Bus Station"
    print "13A Gold Souq Bus Station–Al Qusais Bus Station"
    print "17 Al Sabkha Bus Station–Al Qusais Bus Station"
    print "22 Healthcare City–Al Nahda 1"
    print "31 Gold Souq Bus Station–Oud Al Mateena"
    print "64 Gold Souq Bus Station–Ras Al Khor"
    print "C18 Shaikh Rashid Colony, Al Qusais–Lamcy Plaza"
    print "C19 Ghubaiba Bus Station–Al Qusais Industrial Area"
    print "X28 Lulu Village–Nakheel MS"
if(To=="stadium"):
    print "13-Gold Souq Bus Station–Al Qusais Bus Station"
    print "13A Gold Souq Bus Station–Al Qusais Bus Station"
    print "17 Al Sabkha Bus Station–Al Qusais Bus Station"
    print "22 Healthcare City–Al Nahda 1"
    print "64 Gold Souq Bus Station–Ras Al Khor"
    print "C18 Shaikh Rashid Colony, Al Qusais–Lamcy Plaza"
    print "C19 Ghubaiba Bus Station–Al Qusais Industrial Area"
    print "X28 Lulu Village–Nakheel MS"
if(To=="al qiyadah"):
    print "C9-Al Satwa Bus Station–Hor Al Anz East"
if(To=="abu hail"):
    print "13 Gold Souq Bus Station–Al Qusais Bus Station"
    print "13A Gold Souq Bus Station–Al Qusais Bus Station"
    print "48 Mamzar, Century Mall–Al Rashidiya MS"
    print "C2 Zabeel Park–Airport Terminal 2"
    print "C3 Hor Al Anz Bus Station–Karama Bus Station"
    print "C7 Hor Al Anz Bus Station–Healthcare City"
    print "C9 Satwa Bus Station–Hor Al Anz East"
    print "C19 Ghubaiba Bus Station–Al Qusais Industrial Area"
    print "X28 Lulu Village–Nakheel MS"
if(To=="abu bakr al siddique"):
    print "13 Gold Souq Bus Station–Al Qusais Bus Station"
    print "13A Gold Souq Bus Station–Al Qusais Bus Station"
    print "48 Mamzar, Century Mall–Al Rashidiya MS"
    print "C2 Zabeel Park–Airport Terminal 2"
    print "C19 Ghubaiba Bus Station–Al Qusais Industrial Area" 
    print "x28 Lulu Village–Nakheel MS" 
if(To=="salah al din"):
    print "10-Gold Souq Bus Station–Al Quoz Bus Station"
    print "13-Gold Souq Bus Station–Al Qusais Bus Station"
    print "13A-Gold Souq Bus Station–Al Qusais Bus Station"
    print "C2-Zabeel Park–Airport Terminal 2"
    print "C28-Gold Souq Bus Station–Mamzar Beach Park"
if(To=="union"):
    print "4-Gold Souq Bus Station–Rashidiya MS"
    print "11A-Gold Souq Bus Station–Al Awir"
    print "27-Gold Souq Bus Station–Dubai Mall"
    print "64A-Gold Souq Bus Station–Ras Al Khor"
    print "C1-Airport Terminal 3–Satwa Bus Station"
    print "C2-Zabeel Park–Airport Terminal 2"
    print "C4-Gold Souq Bus Station–Jadaf"
    print "C5-Gold Souq Bus Station–Ghubaiba Bus Station"
    print "C7-Hor Al Anz Bus Station–Healthcare City"
    print "C9-Satwa Bus Station–Hor Al Anz East"
    print "C28-Gold Souq Bus Station–Mamzar Beach Park"
    print "C55-Gold Souq Bus Station–Ghubaiba Bus Station"
    print "X94-Gold Souq Bus Station–Dubai Investment Park"
if(To=="baniyas square"):
    print "17-Al Sabkha Bus Station–Al Qusais Bus Station" 
    print "64A-Gold Souq Bus Station–Ras Al Khor"
if(To=="palm deira"):
    print "8-Gold Souq Bus Station–Al Mina Al Siyahi" 
    print "C1-Airport Terminal 3–Satwa Bus Station"
    print "C2-Zabeel Park–Airport Terminal 2" 
    print "C3-Hor Al Anz Bus Station-Karama Bus Station" 
    print "C7-Hor Al Anz Bus Station–Healthcare City"
    print "C9-Satwa Bus Station–Hor Al Anz East"
    print "C18-Shaikh Rashid Colony, Al Qusais–Lamcy Plaza"
    print "C55-Gold Souq Bus Station–Ghubaiba Bus Station"
    print "X10-Gold Souq Bus Station–Al Qouz Bus Station"
    print "X13-LuLu Village–Al Satwa Bus Station"
    print "X23-Gold Souq Bus Station–International City"
if(To=="al ras"):
    print "27-Gold Souq Bus Station–Dubai Mall"
    print "53-Ghubaiba Bus Station–International City"
    print "C2-Zabeel Park–Airport Terminal 2"
    print "C4-Gold Souq Bus Station–Jadaf"
    print "C7-Hor Al Anz Bus Station–Healthcare City"
    print "C9-Satwa Bus Station–Hor Al Anz East"
    print "C28-Gold Souq Bus Station–Mamzar Beach Park"
    print "C55-Gold Souq Bus Station–Ghubaiba Bus Station"
if(To=="al ghubaiba"):
    print "8-Gold Souq Bus Station–Al Mina Al Siyahi"
    print "C5-Gold Souq Bus Station–Ghubaiba Bus Station"
    print "C7-Hor Al Anz Bus Station–Healthcare City"
    print "C9-Satwa Bus Station–Hor Al Anz East"
    print "X13-LuLu Village–Al Satwa Bus Station"    
if(To=="al fahidi"):
    print "21-Ghubaiba Bus Station–Al Quoz Ind. Area 4"
    print "33 Ghubaiba Bus Station–Qusais Bus Station"
    print "42 Ghubaiba Bus Station–Airport Terminal 1" 
    print "44 Ghubaiba Bus Station–Dubai Festival City" 
    print "61 Ghubaiba Bus Station–Ras Al Khor"
    print "61D Ghubaiba Bus Station-Nad Al Sheba Clinic"
    print "66 Ghubaiba Bus Station–Faqa Terminus"
    print "67 Ghubaiba Bus Station–Endurance City Terminus"
    print "91 Ghubaiba Bus Station–Jebel Ali Bus Station"
    print "C1 Airport Terminal 3–Satwa Bus Station"
    print "C2 Zabeel Park–Airport Terminal 2"
    print "C3 Hor Al Anz Bus Station–Karama Bus Station"
    print "C5 Gold Souq Bus Station–Ghubaiba Bus Station"
    print "C7 Hor Al Anz Bus Station–Healthcare City"
    print "C18 Shaikh Rashid Colony, Al Qusais–Lamcy Plaza"
    print "C19 Ghubaiba Bus Station-Al Qusais Industrial Area"
    print "C55 Gold Souq Bus Station-Ghubaiba Bus Station"
    print "X23 Gold Souq Bus Station–International City"